pipeline {  
  environment {
    registry = "yogendra/piper-2020-day-2-lab-3"
    registryCredential = 'dockerhub'
  }  
  agent any  
  stages {
    // git url: 'https://github.com/yogendra/Piper-2020.git'
    stage('Checkout'){
      steps {
        checkout scm
      }
    }
    stage('Building image') {
      steps{
        script {
          imageName = registry + ":$BUILD_NUMBER"
          context = "./Day 2/Lab 03 - Part 1 - Containerising an App"      
          docker.build(imageName, context)
        }
      }
    }
  }
}
