pipeline {  
  environment {
    registry = "yogendra/piper-2020-day-2-lab-3"
    registryCredential = 'dockerhub'
  }  
  agent any  
  stages {
    stage('Building image') {
      steps{
        script {
          docker.build registry + ":$BUILD_NUMBER"
        }
      }
    }
  }
}
